name: doc

on:
  push:
    branches: [main, 'doc/*']
  pull_request:
    branches: [main]

jobs:
  doc:
    runs-on: ubuntu-latest
    container: opendilab/didrive-ci:0.3.4

    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: |
          python3 -m pip install .[doc]
          make -C ./docs html
          mv docs/build/html public
          rm -rf docs/build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch