name: install

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: |
          python -m pip install .
          wget http://opendilab.org/download/DI-drive/carla-0.9.9-py3.7-linux-x86_64.egg
          easy_install carla-0.9.9-py3.7-linux-x86_64.egg
          python -c 'import carla'
          python -c 'import metadrive'
          python -c 'import core'
